"use strict";

window.GLOSSARY_REVIEWED_TOPICS = [
  "01-osnovy-radiozviazku",
  "02-tehnika-bezpeky",
  "03-radiohvyli-radiozviazok-zavady",
  "04-pobudova-radiostantsii-antenny",
  "05-harris-ukh",
  "06-harris-kh",
  "07-harris-kh-ekspluatatsiia",
  "08-harris-kh-programuvannia",
  "09-tooway",
  "10-mototrbo"
];

window.GLOSSARY_TERMS = [
  { term: "RSSI", full: "Received Signal Strength Indication", uk: "показник рівня прийнятого сигналу", description: "У роумінгу MOTOTRBO падіння RSSI домашнього ретранслятора нижче встановленого порога запускає пошук іншого ретранслятора за списком роумінгу.", topics: [10] },
  { term: "IP Site Connect", full: "IP Site Connect", uk: "система об’єднаних ретрансляторів MOTOTRBO", description: "Роумінг у цій системі дозволяє перемикатися між ретрансляторами відповідно до рівня сигналу. Передбачено автоматичний і ручний вибір.", topics: [10] },
  { term: "RAS", full: "Обмежений доступ до системи", uk: "ключ обмеження доступу", description: "Ключ, за яким ретранслятор MOTOTRBO ідентифікує свої радіостанції. Використовується на каналах через ретранслятор; довжина — 6–24 символи.", topics: [10] },
  { term: "АНД", full: "Антена направлена — директорна", uk: "директорна антена", description: "Антена для зв’язку з віддаленим кореспондентом, координати якого відомі. У матеріалі MOTOTRBO наведено ширину діаграми за азимутом не більш як 60°.", topics: [10] },
  { term: "AMBE+2", full: "Advanced Multi-Band Excitation +2", uk: "вокодер AMBE+2", description: "Вокодер для кодування мовлення; зазначений у характеристиках портативних і автомобільних радіостанцій MOTOTRBO.", topics: [10] },
  { term: "ARC4", full: "ARC4", uk: "алгоритм покращеної конфіденційності", description: "У розглянутих радіостанціях MOTOTRBO — режим із 40-бітним ключем, представленим до 10 шістнадцятковими символами.", topics: [10] },
  { term: "UHF", full: "Ultra High Frequency", uk: "ультрависокі частоти", description: "Діапазон 300–3000 МГц. Розглянуті UHF-виконання радіостанцій MOTOTRBO працюють у смузі 403–527 МГц.", topics: [10] },
  { term: "TPL", full: "Tone Private Line", uk: "тональний код шумоподавлювача", description: "Тональний код для вибіркового відкривання шумоподавлювача в аналоговому каналі; не шифрує мовлення.", topics: [10] },
  { term: "DPL", full: "Digital Private Line", uk: "цифровий код шумоподавлювача", description: "Цифровий код для вибіркового відкривання шумоподавлювача в аналоговому каналі; не шифрує мовлення.", topics: [10] },
  { term: "OTAP", full: "Over-the-Air Programming", uk: "програмування через радіоканал", description: "Передавання налаштувань радіостанції через радіоканал. У таблиці індикації портативної MOTOTRBO пов’язане із зеленим блиманням.", topics: [10] },
  { term: "DVB-S", full: "Digital Video Broadcasting — Satellite", uk: "цифрове супутникове мовлення", description: "У презентації TOOWAY так позначено технологію прямого каналу від центральної станції до абонентів.", topics: [9] },
  { term: "MF-TDMA", full: "Multi-Frequency Time-Division Multiple Access", uk: "багаточастотний множинний доступ із часовим розділенням", description: "Технологія зворотного каналу TOOWAY: станції використовують різні несучі та часові інтервали; одна станція одночасно працює на одній несучій.", topics: [9] },
  { term: "VoIP", full: "Voice over Internet Protocol", uk: "голос через IP-мережу", description: "Передавання голосового трафіку через IP-мережу; VoIP-шлюз підключає до неї аналогові телефонні апарати.", topics: [9] },
  { term: "FXS", full: "Foreign Exchange Station", uk: "абонентський телефонний інтерфейс", description: "Порт VoIP-шлюзу для підключення аналогового телефонного апарата. У СТК-2 два шлюзи по два FXS-порти.", topics: [9] },
  { term: "ARP", full: "Address Resolution Protocol", uk: "протокол визначення адрес", description: "Пов’язує IPv4-адреси з MAC-адресами у локальній мережі. У MikroTik таблицю IP → ARP використовують для визначення адрес підключених пристроїв.", topics: [9] },
  { term: "DNS", full: "Domain Name System", uk: "система доменних імен", description: "Система зіставлення доменних імен з адресами; у показаних налаштуваннях TCP/IPv4 адресу DNS-сервера отримують автоматично.", topics: [9] },
  { term: "SIP", full: "Session Initiation Protocol", uk: "протокол ініціювання сеансів", description: "Протокол установлення й керування сеансами IP-телефонії. У VoIP-шлюзі SIP User ID визначає ідентифікатор абонента.", topics: [9] },
  { term: "КЗІ", full: "Криптографічний захист інформації", uk: "криптографічний захист інформації", description: "На схемі СТК-2 окрема апаратура КЗІ розміщена між маршрутизатором і VoIP-шлюзом закритої телефонної мережі.", topics: [9] },
  { term: "СТК-2", full: "Супутниковий телекомунікаційний комплект", uk: "супутниковий телекомунікаційний комплект", description: "Автономний комплекс для телефонного зв’язку та передавання даних через супутниковий канал TOOWAY.", topics: [9] },
  { term: "3G", full: "Third Generation", uk: "третє покоління КХ-протоколів", description: "Автоматизований режим встановлення КХ-зв'язку за STANAG 4538.", topics: [6, 7, 8] },
  { term: "3G+", full: "Third Generation Plus", uk: "розширений режим третього покоління", description: "Одночасно контролює мережі 3G та ALE; доступний у RF-7800H-MP.", topics: [6, 7] },
  { term: "AES", full: "Advanced Encryption Standard", uk: "розширений стандарт шифрування", description: "Симетричний алгоритм шифрування; у матеріалах згадано ключі 128 і 256 біт.", topics: [4, 5, 6, 8, 10] },
  { term: "ALE", full: "Automatic Link Establishment", uk: "автоматичне встановлення зв'язку", description: "Сканує запрограмовані канали, оцінює їх та автоматизує встановлення КХ-з'єднання.", topics: [6, 7, 8] },
  { term: "AM", full: "Amplitude Modulation", uk: "амплітудна модуляція", description: "Аналогова модуляція, за якої інформація змінює амплітуду несучої.", topics: [4, 5] },
  { term: "AMD", full: "Automatic Message Display", uk: "автоматичне відображення повідомлень", description: "Короткі заздалегідь створені текстові повідомлення в ALE; у матеріалі до 100 символів.", topics: [7] },
  { term: "AME", full: "Amplitude Modulation Equivalent", uk: "еквівалент амплітудної модуляції", description: "Режим сумісності з радіостанціями старого парку.", topics: [6] },
  { term: "ANW2", full: "Adaptive Networking Wideband Waveform 2", uk: "адаптивна широкосмугова мережева форма сигналу", description: "Мережева форма сигналу для пакетного передавання голосу й даних.", topics: [5] },
  { term: "ANW2C", full: "Adaptive Networking Wideband Waveform 2C", uk: "адаптивна широкосмугова мережева форма сигналу", description: "Самоорганізована широкосмугова MANET для голосу й даних.", topics: [5] },
  { term: "APPS", full: "Applications", uk: "застосунки", description: "Функціональна назва клавіші 7, що відкриває прикладне меню радіостанції.", topics: [5] },
  { term: "ARCS", full: "Automatic Radio Control System", uk: "система автоматичного керування радіозв'язком", description: "Автоматизує вибір каналу та встановлення зв'язку в 3G.", topics: [6] },
  { term: "ARQ", full: "Automatic Repeat reQuest", uk: "автоматичний запит повторення", description: "Протокол із повторним передаванням пошкоджених або втрачених блоків даних.", topics: [6] },
  { term: "ASK", full: "Amplitude Shift Keying", uk: "амплітудна маніпуляція", description: "Цифрове кодування символів дискретними значеннями амплітуди.", topics: [4, 5] },
  { term: "AVS", full: "Analog Voice Security", uk: "аналоговий захист мови", description: "Аналогове скремблювання голосу в радіостанціях HARRIS КХ.", topics: [6] },
  { term: "BIT", full: "Built-In Test", uk: "вбудований тест", description: "Самодіагностика вузлів радіостанції з відображенням стану або результатів.", topics: [5, 6, 7] },
  { term: "BIOS", full: "Basic Input/Output System", uk: "базова система введення-виведення", description: "Системне програмне забезпечення початкової перевірки та запуску обладнання.", topics: [6] },
  { term: "CID", full: "Combat Net ID", uk: "ідентифікатор бойової радіомережі", description: "Ідентифікатор мережі, який переглядають разом з ім'ям радіостанції.", topics: [5] },
  { term: "CITADEL", full: "CITADEL", uk: "алгоритм шифрування HARRIS", description: "Фірмове сімейство засобів шифрування, зокрема варіант CITADEL-128.", topics: [4, 5, 6] },
  { term: "CLR", full: "Clear", uk: "очистити; відкритий голос", description: "На клавіатурі - очищення поля або повернення в меню; у таблиці вокодерів - аналогова телефонія без вокодера.", topics: [5, 6, 7] },
  { term: "COMSEC", full: "Communications Security", uk: "безпека зв'язку", description: "Захист змісту зв'язку, зокрема криптографічними ключами й алгоритмами.", topics: [5, 6, 8] },
  { term: "CPA", full: "Communications Planning Application", uk: "застосунок планування зв'язку", description: "Програмне забезпечення для створення та завантаження конфігурації радіостанції.", topics: [5, 6, 8] },
  { term: "CT", full: "Cipher Text", uk: "зашифрований режим", description: "Режим захищеної роботи із застосуванням завантажених ключів.", topics: [5, 6, 7, 8] },
  { term: "Channel Group", full: "Channel Group", uk: "канальна група", description: "Набір каналів одного режиму, який призначають мережі ALE або частотному плану 3G.", topics: [8] },
  { term: "CVSD", full: "Continuously Variable Slope Delta", uk: "дельта-модуляція зі змінним нахилом", description: "Цифровий вокодер для телефонії; у темі HARRIS УКХ наведено 16000 біт/с.", topics: [5, 6] },
  { term: "CW", full: "Continuous Wave", uk: "безперервна несуча", description: "Телеграфний режим із вмиканням і вимиканням несучої за знаками Морзе.", topics: [6] },
  { term: "CWR", full: "Country Wide Repeater", uk: "ретрансляторна мережа великого покриття", description: "FIX-мережа з MACA2 та IP-магістраллю, у якій абонент автоматично реєструється на доступному вузлі.", topics: [5] },
  { term: "DEL", full: "Delete", uk: "видалити", description: "Екранна клавіша видалення символу під час редагування.", topics: [5] },
  { term: "DSP", full: "Digital Signal Processor", uk: "цифровий сигнальний процесор", description: "Спеціалізований процесор цифрової обробки сигналів.", topics: [5] },
  { term: "DV24", full: "Digital Voice 2400 bit/s", uk: "цифровий голос 2400 біт/с", description: "Цифровий вокодер зі швидкістю 2400 біт/с.", topics: [6] },
  { term: "DV6", full: "Digital Voice 600 bit/s", uk: "цифровий голос 600 біт/с", description: "Низькошвидкісний цифровий вокодер зі швидкістю 600 біт/с.", topics: [6] },
  { term: "ENT", full: "Enter", uk: "введення або підтвердження", description: "Клавіша підтвердження вибору чи переходу до підсвіченого пункту.", topics: [5, 6, 7] },
  { term: "FCS", full: "Free Channel Search", uk: "пошук вільного каналу", description: "Функція вибору доступного каналу перед роботою мережі.", topics: [5] },
  { term: "FDD", full: "Frequency Division Duplex", uk: "частотний дуплекс", description: "Передавання і приймання рознесені на різні частоти.", topics: [1] },
  { term: "FF", full: "Fixed Frequency", uk: "фіксована частота", description: "Робота на заздалегідь установленій незмінній робочій частоті.", topics: [5] },
  { term: "FIX", full: "Fixed Frequency", uk: "режим фіксованої частоти", description: "Режим роботи на запрограмованому каналі без перескоку частоти.", topics: [5, 6, 7, 8] },
  { term: "FM", full: "Frequency Modulation", uk: "частотна модуляція", description: "Аналогова модуляція, за якої інформація змінює частоту несучої.", topics: [4, 5, 6, 8] },
  { term: "FSK", full: "Frequency Shift Keying", uk: "частотна маніпуляція", description: "Цифрове кодування символів дискретними значеннями частоти.", topics: [4, 5, 6] },
  { term: "GPS", full: "Global Positioning System", uk: "глобальна система позиціонування", description: "Використовується для координат і точної синхронізації часу.", topics: [4, 5, 6, 7] },
  { term: "GPS-APR", full: "GPS Automatic Position Reporting", uk: "автоматичне передавання GPS-позиції", description: "Функція формування, надсилання та перегляду звітів із координатами.", topics: [7] },
  { term: "GPS-TOD", full: "GPS Time of Day", uk: "час доби за GPS", description: "Меню перегляду точної часової основи, отриманої або синхронізованої через GPS.", topics: [7] },
  { term: "HF", full: "High Frequency", uk: "високі частоти; КХ", description: "Міжнародне позначення діапазону високих частот, що відповідає КХ.", topics: [6, 8, 10] },
  { term: "HOP", full: "Frequency Hopping", uk: "режим перескоку частоти", description: "Робота зі синхронізованою зміною частот за завантаженим Hop Set.", topics: [6, 7, 8] },
  { term: "HUB", full: "Hold-Up Battery", uk: "внутрішня резервна батарея", description: "Підтримує збереження запрограмованих параметрів і завантажених даних радіостанції, коли основне живлення від'єднане.", topics: [7] },
  { term: "Hopset", full: "Hopset", uk: "набір параметрів перескоку частоти", description: "Набір частотних і часових параметрів, за якими працює мережа HOP.", topics: [8] },
  { term: "HH", full: "Handheld", uk: "портативна радіостанція", description: "Позначення ручного портативного виконання у назві моделі.", topics: [5] },
  { term: "ID", full: "Identification", uk: "ідентифікатор", description: "Унікальне позначення об'єкта, мережі або радіостанції.", topics: [5] },
  { term: "IP", full: "Internet Protocol", uk: "інтернет-протокол", description: "Мережевий протокол адресації та передавання пакетів даних.", topics: [5, 6, 7] },
  { term: "KDU", full: "Keypad Display Unit", uk: "клавішно-дисплейний пристрій", description: "Виносний або вбудований орган керування з клавіатурою та дисплеєм.", topics: [4, 5, 6] },
  { term: "LCD", full: "Liquid Crystal Display", uk: "рідкокристалічний дисплей", description: "Дисплей передньої панелі, який перевіряється інтерактивним тестом.", topics: [5] },
  { term: "LDV", full: "Last Ditch Voice", uk: "голос останньої надії", description: "Записане голосове повідомлення для дуже складних умов проходження; використовується в 3G.", topics: [6, 7] },
  { term: "LQA", full: "Link Quality Analysis", uk: "аналіз якості каналу", description: "Оцінювання каналів перед викликом; для тесту станції повинні перебувати в режимі сканування.", topics: [7] },
  { term: "LOS", full: "Line of Sight", uk: "пряма видимість", description: "Радіозв'язок у межах прямої або близької до прямої видимості.", topics: [5] },
  { term: "LSB", full: "Lower Sideband", uk: "нижня бокова смуга", description: "Односмугова модуляція з передаванням нижньої бокової смуги.", topics: [6] },
  { term: "LT", full: "Light", uk: "підсвітка", description: "Функціональна назва клавіші 3 для керування підсвіткою.", topics: [5] },
  { term: "MACA", full: "Multiple Access Collision Avoidance", uk: "множинний доступ із запобіганням колізіям", description: "Керує доступом кількох станцій до спільного каналу.", topics: [5] },
  { term: "MACA2", full: "Multiple Access Collision Avoidance, generation 2", uk: "друге покоління MACA", description: "Розширений механізм доступу до каналу для спільної роботи голосу й даних.", topics: [5] },
  { term: "MANET", full: "Mobile Ad Hoc Network", uk: "мобільна самоорганізована мережа", description: "Мережа без постійної центральної інфраструктури, вузли якої можуть змінювати маршрути.", topics: [5] },
  { term: "MELP", full: "Mixed Excitation Linear Prediction", uk: "лінійне передбачення зі змішаним збудженням", description: "Сімейство низькошвидкісних цифрових вокодерів.", topics: [5, 6] },
  { term: "ME24", full: "MELP 2400 bit/s", uk: "MELP зі швидкістю 2400 біт/с", description: "Позначення вокодера MELP 2400 біт/с.", topics: [6] },
  { term: "ME12", full: "MELP 1200 bit/s", uk: "MELP зі швидкістю 1200 біт/с", description: "Позначення вокодера MELP 1200 біт/с.", topics: [6] },
  { term: "ME6", full: "MELP 600 bit/s", uk: "MELP зі швидкістю 600 біт/с", description: "Позначення вокодера MELP 600 біт/с.", topics: [6] },
  { term: "MIL-STD-188-110B", full: "Military Standard 188-110B", uk: "військовий стандарт модемів даних", description: "Стандарт параметрів і режимів модемного передавання даних КХ-каналом.", topics: [6] },
  { term: "MIL-STD-188-141A/B", full: "Military Standard 188-141A/B", uk: "військовий стандарт ALE", description: "Стандарт автоматичного встановлення КХ-зв'язку ALE.", topics: [6] },
  { term: "PGM", full: "Programming", uk: "програмування", description: "Функціональна назва клавіші 9, що відкриває меню програмування.", topics: [5, 6, 7] },
  { term: "PPP", full: "Point-to-Point Protocol", uk: "протокол точка-точка", description: "Канальний протокол прямого з'єднання двох мережевих вузлів.", topics: [6] },
  { term: "ppm", full: "parts per million", uk: "частин на мільйон", description: "Одиниця відносної похибки; у характеристиках описує стабільність частоти.", topics: [5] },
  { term: "Key Ring", full: "Key Ring", uk: "набір ключів", description: "Об'єкт CPA для зберігання та призначення ключів шифрування мережам КХ-зв'язку.", topics: [8] },
  { term: "PT", full: "Plain Text", uk: "відкритий режим", description: "Робота без шифрування змісту повідомлення.", topics: [5, 6, 7, 8] },
  { term: "PTT", full: "Push-to-Talk", uk: "натисни, щоб говорити", description: "Тангента, яка переводить радіостанцію з приймання на передавання.", topics: [1, 5, 6, 7, 10] },
  { term: "PSK", full: "Phase Shift Keying", uk: "фазова маніпуляція", description: "Цифрова модуляція, у якій дані кодуються змінами фази несучої.", topics: [6] },
  { term: "QL", full: "Quicklook", uk: "сімейство режимів Quicklook", description: "Узагальнене позначення режимів ППРЧ Quicklook.", topics: [5] },
  { term: "QL1A", full: "Quicklook 1A", uk: "режим Quicklook 1A", description: "Режим ППРЧ для голосу й даних зі швидкістю даних 16 кбіт/с.", topics: [5] },
  { term: "QL2", full: "Quicklook 2", uk: "режим Quicklook 2", description: "Голосовий режим ППРЧ зі швидким перестроюванням частоти.", topics: [5] },
  { term: "QL3", full: "Quicklook 3", uk: "режим Quicklook 3", description: "Голосовий режим ППРЧ із кількома швидкостями перестроювання та синхронізацією TOD або GPS.", topics: [5] },
  { term: "QLW", full: "Quicklook Wide", uk: "широкосмуговий Quicklook", description: "ППРЧ-режим із каналом 75 кГц, MACA2, голосом і даними.", topics: [5] },
  { term: "RAM", full: "Random Access Memory", uk: "оперативна пам'ять", description: "Енергозалежна пам'ять, яку перевіряє вбудована діагностика.", topics: [5] },
  { term: "RF", full: "Radio Frequency", uk: "радіочастота", description: "Позначення радіочастотного обладнання або тракту; використовується у назвах моделей.", topics: [5, 8] },
  { term: "RS-232", full: "Recommended Standard 232", uk: "стандарт послідовного інтерфейсу", description: "Стандарт дротового послідовного обміну даними між пристроями.", topics: [6] },
  { term: "Rx", full: "Receive", uk: "приймання", description: "Позначення приймального тракту або частоти приймання.", topics: [5, 7] },
  { term: "SMS", full: "Short Message Service", uk: "служба коротких повідомлень", description: "Передавання коротких текстових повідомлень у режимі 3G.", topics: [7, 8] },
  { term: "SNR", full: "Signal-to-Noise Ratio", uk: "відношення сигнал/шум", description: "Показник співвідношення потужності корисного сигналу до шуму.", topics: [6] },
  { term: "SQL", full: "Squelch", uk: "шумоподавлення", description: "Функція приглушення шуму приймача за відсутності корисного сигналу.", topics: [5, 6] },
  { term: "STC", full: "Satellite TDMA Capability", uk: "супутникова можливість TDMA", description: "Режим роботи через військовий супутниковий ретранслятор.", topics: [5] },
  { term: "STANAG", full: "NATO Standardization Agreement", uk: "угода НАТО зі стандартизації", description: "Система стандартів НАТО; номер після STANAG визначає конкретний документ.", topics: [6] },
  { term: "SWR", full: "Standing Wave Ratio", uk: "коефіцієнт стоячої хвилі", description: "Показник узгодження антени з фідером; у конспекті також використовується КСХ і VSWR.", topics: [4] },
  { term: "TDD", full: "Time Division Duplex", uk: "часовий дуплекс", description: "Передавання і приймання використовують одну частоту в різні часові інтервали.", topics: [1] },
  { term: "TDMA", full: "Time Division Multiple Access", uk: "множинний доступ із часовим розподілом", description: "Кілька станцій ділять канал за призначеними часовими слотами.", topics: [5, 7] },
  { term: "TNC", full: "Threaded Neill-Concelman Connector", uk: "різьбовий коаксіальний роз'єм TNC", description: "Тип ВЧ-роз'єму антенного порту.", topics: [5] },
  { term: "TNW", full: "Tactical Networking Waveform", uk: "тактична мережева форма сигналу", description: "Вузькосмугова ППРЧ-мережа з TDMA для голосу й даних.", topics: [5] },
  { term: "TOD", full: "Time of Day", uk: "час доби", description: "Еталон часу, потрібний для синхронної роботи мереж із перескоком частоти.", topics: [5, 7, 8] },
  { term: "TOD Mask", full: "Time of Day Mask", uk: "маска часу доби", description: "Параметр HOP, який CPA може формувати автоматично для синхронізованого перескоку частоти.", topics: [8] },
  { term: "TRANSEC", full: "Transmission Security", uk: "безпека передавання", description: "Захист структури та параметрів радіопередавання, зокрема ППРЧ.", topics: [5, 6] },
  { term: "Tx", full: "Transmit", uk: "передавання", description: "Позначення передавального тракту або частоти передавання.", topics: [5, 7] },
  { term: "USB", full: "Upper Sideband / Universal Serial Bus", uk: "верхня бокова смуга / універсальна послідовна шина", description: "У режимах HARRIS КХ означає верхню бокову смугу; у контексті кабелю, порту або підключення - Universal Serial Bus.", contexts: { bus: { full: "Universal Serial Bus", uk: "універсальна послідовна шина", description: "Стандарт дротового підключення; у цьому контексті йдеться про USB-кабель або інтерфейс DIRECT USB, а не про вид модуляції." } }, topics: [5, 6, 7, 8] },
  { term: "UTC", full: "Coordinated Universal Time", uk: "всесвітній координований час", description: "Стандарт часу, від якого задають часові пояси та зміщення.", topics: [5] },
  { term: "VAA", full: "Vehicular Amplifier Adapter", uk: "автомобільний адаптер-підсилювач", description: "Адаптер для інтеграції портативної радіостанції у возиму конфігурацію.", topics: [5] },
  { term: "VHF", full: "Very High Frequency", uk: "дуже високі частоти; УКХ", description: "Діапазон дуже високих частот; у матеріалах відповідає УКХ-контексту.", topics: [5, 6, 10] },
  { term: "VR-TNW", full: "Voice Repeater TNW", uk: "голосовий ретранслятор TNW", description: "Ретрансляторний варіант мережі TNW для голосового зв'язку.", topics: [5] },
  { term: "VSWR", full: "Voltage Standing Wave Ratio", uk: "коефіцієнт стоячої хвилі за напругою", description: "Показник узгодження антени з фідером; відповідає КСХ за напругою.", topics: [4, 7] },
  { term: "WBFSK", full: "Wideband Frequency Shift Keying", uk: "широкосмугова частотна маніпуляція", description: "Широкосмуговий модем для роботи в УКХ, доступний RF-7800H-MP.", topics: [6] },
  { term: "WBHF", full: "Wideband High Frequency", uk: "широкосмуговий КХ", description: "Широкосмуговий модем 3G зі швидкістю до 120 кбіт/с.", topics: [6, 8] },
  { term: "Web UI", full: "Web User Interface", uk: "вебінтерфейс користувача", description: "Браузерний інтерфейс для перегляду та налаштування параметрів радіостанції.", topics: [5] },
  { term: "XDL", full: "HARRIS proprietary designation", uk: "фірмове позначення HARRIS", description: "Модем для 3G зі швидкостями 75-9600 біт/с.", topics: [6] },
  { term: "Z0", full: "Characteristic Impedance", uk: "хвильовий опір", description: "Характеристичний опір фідера або лінії передавання.", topics: [4] },
  { term: "АКБ", full: "акумуляторна батарея", uk: "", description: "Джерело живлення радіостанції, стан і заряд якого контролює оператор.", topics: [5, 6] },
  { term: "АФП", full: "антенно-фідерний пристрій", uk: "", description: "Сукупність антени, фідера та допоміжних елементів для передавання ВЧ енергії.", topics: [2, 4] },
  { term: "АЩП", full: "антенно-щогловий пристрій", uk: "", description: "Щогла, відтяжки, троси, кріплення та інші елементи розгортання антени.", topics: [2] },
  { term: "КДП", full: "клавішно-дисплейний пристрій", uk: "", description: "Орган керування радіостанцією з клавіатурою та дисплеєм; англійське позначення KDU.", topics: [4, 5, 6] },
  { term: "ККД", full: "коефіцієнт корисної дії", uk: "", description: "Відношення корисної вихідної потужності до спожитої потужності.", topics: [4] },
  { term: "КСХ", full: "коефіцієнт стоячої хвилі", uk: "", description: "Показує якість узгодження антени з фідером і пов'язаний із часткою відбитої потужності.", topics: [2, 4, 6, 7] },
  { term: "КХ", full: "короткі хвилі", uk: "", description: "Радіодіапазон, у якому можливе далеке поширення завдяки взаємодії з іоносферою.", topics: [3, 4, 6, 7, 8] },
  { term: "ЛЕП", full: "лінія електропередачі", uk: "", description: "Інфраструктура передавання електроенергії, яка може бути джерелом промислових радіозавад.", topics: [3] },
  { term: "ПЕОМ", full: "персональна електронно-обчислювальна машина", uk: "", description: "Комп'ютер, який використовується для програмування або керування радіостанцією.", topics: [4, 6] },
  { term: "ППРЧ", full: "псевдовипадкове перестроювання робочої частоти", uk: "", description: "Синхронна швидка зміна робочої частоти за визначеним законом для підвищення захищеності.", topics: [4, 5, 6, 7] },
  { term: "РЕБ", full: "радіоелектронна боротьба", uk: "", description: "Дії та засоби для розвідки, впливу на радіоелектронні системи й захисту власних засобів.", topics: [1, 3] },
  { term: "ЗСУ", full: "Збройні Сили України", uk: "", description: "Військове формування України, у системі якого організовується службовий радіозв'язок.", topics: [1] },
  { term: "УКХ", full: "ультракороткі хвилі", uk: "", description: "Радіохвилі, поширення яких переважно обмежене радіогоризонтом і рельєфом.", topics: [3, 4, 5, 6, 8] }
];
