"use strict";
// Generated from questions.json by npm run build:quiz.
window.QUIZ_CONFIG = {
  id: "topic5-harris",
  label: "ВОС-420 · HARRIS RF-7850M-HH",
  title: "Розширена вікторина HARRIS",
  quizSize: 30,
  questions: [
    {
      id: "t5-01",
      topic: "Призначення",
      question: "Для якої ланки призначена RF-7850M-HH?",
      correct: "Для тактичної ланки управління",
      wrong: [
        "Тільки для цивільного мовлення",
        "Лише для супутникової навігації",
        "Виключно для стаціонарної телефонії",
        "Для оперативно-стратегічної ланки управління",
        "Для стратегічної ланки управління",
        "Для авіаційного диспетчерського зв'язку",
      ],
      explanation: "Радіостанція забезпечує тактичний УКХ зв'язок голосом і даними.",
      reference: "#pryznachennia",
    },
    {
      id: "t5-02",
      topic: "Можливості",
      question: "Які види інформації підтримує радіостанція?",
      correct: "Голос і дані",
      wrong: [
        "Тільки голос",
        "Тільки координати",
        "Лише відео",
        "Голос і відео без передавання даних",
      ],
      explanation: "RF-7850M-HH працює як у телефонному режимі, так і з даними.",
      reference: "#pryznachennia",
    },
    {
      id: "t5-03",
      topic: "Можливості",
      question: "У яких режимах захисту може працювати станція?",
      correct: "У відкритому PT і захищеному CT",
      wrong: [
        "Тільки у відкритому",
        "Тільки без передавання",
        "Лише в аналоговому",
        "Лише у захищеному CT",
      ],
      explanation: "PT означає відкриту, а CT - шифровану роботу.",
      reference: "#pryznachennia",
    },
    {
      id: "t5-04",
      topic: "Діапазон",
      question: "Який робочий діапазон RF-7850M-HH?",
      correct: "30-512 МГц",
      wrong: ["3-30 МГц", "108-174 МГц", "225-400 МГц", "30-225 МГц", "30-108 МГц", "30-88 МГц"],
      explanation: "Посібник наводить безперервне покриття 30-512 МГц.",
      reference: "#chyslovi-kharakterystyky",
    },
    {
      id: "t5-05",
      topic: "Мережі",
      question: "Скільки мереж можна запрограмувати?",
      correct: "25",
      wrong: ["13", "30", "50", "40"],
      explanation: "У пам'яті може бути до 25 мереж.",
      reference: "#chyslovi-kharakterystyky",
    },
    {
      id: "t5-06",
      topic: "Мережі",
      question: "Скільки мереж доступні безпосередньо поворотним перемикачем?",
      correct: "13",
      wrong: ["10", "25", "30", "16"],
      explanation: "Тринадцять позицій перемикача можна прив'язати до запрограмованих мереж.",
      reference: "#chyslovi-kharakterystyky",
    },
    {
      id: "t5-07",
      topic: "Модуляція",
      question: "Що означає AM?",
      correct: "Амплітудна модуляція",
      wrong: [
        "Адаптивна мережа",
        "Амплітудна маніпуляція",
        "Автоматичний модем",
        "Адаптивна модуляція",
      ],
      explanation: "AM є аналоговою амплітудною модуляцією.",
      reference: "#moduliatsii",
    },
    {
      id: "t5-08",
      topic: "Модуляція",
      question: "Що означає FM?",
      correct: "Частотна модуляція",
      wrong: ["Фазова маніпуляція", "Фіксована мережа", "Файловий модем", "Фіксована модуляція"],
      explanation: "FM є аналоговою частотною модуляцією.",
      reference: "#moduliatsii",
    },
    {
      id: "t5-09",
      topic: "Модуляція",
      question: "Що означає ASK?",
      correct: "Амплітудна маніпуляція",
      wrong: [
        "Частотна маніпуляція",
        "Адаптивне сканування",
        "Аналогова синхронізація",
        "Амплітудне сканування ключа",
      ],
      explanation: "ASK є цифровою амплітудною маніпуляцією.",
      reference: "#moduliatsii",
    },
    {
      id: "t5-10",
      topic: "Модуляція",
      question: "Що означає FSK?",
      correct: "Частотна маніпуляція",
      wrong: [
        "Амплітудна маніпуляція",
        "Фіксоване шифрування",
        "Фазове сканування",
        "Частотне сканування ключа",
      ],
      explanation: "FSK передає цифрові дані зміною частоти.",
      reference: "#moduliatsii",
    },
    {
      id: "t5-11",
      topic: "Модуляція",
      question: "У якому діапазоні RF-7850M-HH підтримує AM/ASK?",
      correct: "108,025-512 МГц",
      wrong: ["30-88 МГц", "3-30 МГц", "225,6-512 МГц лише", "30-512 МГц без обмежень"],
      explanation: "Для AM і ASK нижня межа в посібнику становить 108,025 МГц.",
      reference: "#moduliatsii",
    },
    {
      id: "t5-12",
      topic: "Вокодери",
      question: "Яка швидкість MELP?",
      correct: "2400 біт/с",
      wrong: ["1200 біт/с", "16000 біт/с", "64000 біт/с", "6000 біт/с"],
      explanation: "MELP використовується для цифрової телефонії зі швидкістю 2400 біт/с.",
      reference: "#vokodery",
    },
    {
      id: "t5-13",
      topic: "Вокодери",
      question: "Яка швидкість CVSD?",
      correct: "16000 біт/с",
      wrong: ["2400 біт/с", "4800 біт/с", "192000 біт/с", "8000 біт/с"],
      explanation: "CVSD використовується для цифрової телефонії зі швидкістю 16000 біт/с.",
      reference: "#vokodery",
    },
    {
      id: "t5-14",
      topic: "Шифрування",
      question: "Які алгоритми шифрування підтримуються?",
      correct: "Citadel і AES",
      wrong: ["Тільки RSA", "DES і MD5", "Лише аналогове скремблювання", "Citadel і DES"],
      explanation: "У конспекті наведено вбудовані алгоритми Citadel та AES.",
      reference: "#chyslovi-kharakterystyky",
    },
    {
      id: "t5-15",
      topic: "Шифрування",
      question: "Які довжини ключів AES згадано?",
      correct: "128 і 256 біт",
      wrong: ["32 і 64 біти", "512 і 1024 біти", "Лише 40 біт", "64 і 128 біт"],
      explanation: "AES підтримує ключі довжиною 128 або 256 біт.",
      reference: "#chyslovi-kharakterystyky",
    },
    {
      id: "t5-16",
      topic: "Fixed Frequency",
      question: "Який діапазон Fixed Frequency?",
      correct: "30-512 МГц",
      wrong: ["3-30 МГц", "225,6-512 МГц", "243-318,3 МГц", "30-108 МГц"],
      explanation: "Фіксовані мережі використовують увесь робочий діапазон станції.",
      reference: "#rezhymy",
    },
    {
      id: "t5-17",
      topic: "Fixed Frequency",
      question: "Які смуги каналу підтримує Fixed Frequency?",
      correct: "25 або 75 кГц",
      wrong: ["5 або 10 кГц", "1,2 МГц лише", "200 кГц лише", "25 або 50 кГц"],
      explanation: "У режимі FF доступні вузька 25 кГц та опційна 75 кГц смуги.",
      reference: "#rezhymy",
    },
    {
      id: "t5-18",
      topic: "Fixed Frequency",
      question: "Яка максимальна швидкість у каналі 25 кГц?",
      correct: "64 кбіт/с",
      wrong: ["16 кбіт/с", "192 кбіт/с", "1372 кбіт/с", "128 кбіт/с", "32 кбіт/с", "48 кбіт/с"],
      explanation: "Для FF на 25 кГц наводиться до 64 кбіт/с.",
      reference: "#rezhymy",
    },
    {
      id: "t5-19",
      topic: "Fixed Frequency",
      question: "Яка максимальна швидкість у каналі 75 кГц?",
      correct: "192 кбіт/с",
      wrong: ["64 кбіт/с", "16 кбіт/с", "2400 біт/с", "128 кбіт/с"],
      explanation: "Ширший канал дає до 192 кбіт/с.",
      reference: "#rezhymy",
    },
    {
      id: "t5-20",
      topic: "Quicklook",
      question: "Яка швидкість перестроювання Quicklook 1A?",
      correct: "Понад 100 разів/с",
      wrong: [
        "Понад 10 разів/с",
        "Понад 300 разів/с лише",
        "Понад 1000 разів/с лише",
        "Понад 50 разів/с",
      ],
      explanation: "QL1A використовує понад 100 перескоків за секунду.",
      reference: "#rezhymy",
    },
    {
      id: "t5-21",
      topic: "Quicklook",
      question: "Що підтримує Quicklook 1A?",
      correct: "Голос і/або дані",
      wrong: ["Тільки голос", "Тільки GPS", "Лише аналогову AM", "Голос і GPS без інших даних"],
      explanation: "QL1A підтримує і мовний, і даний трафік.",
      reference: "#rezhymy",
    },
    {
      id: "t5-22",
      topic: "Quicklook",
      question: "Яка швидкість перестроювання Quicklook 2?",
      correct: "Понад 300 разів/с",
      wrong: ["Понад 100 разів/с", "Понад 1000 разів/с", "Менше 10 разів/с", "Понад 600 разів/с"],
      explanation: "QL2 швидше за QL1A і орієнтований на голос.",
      reference: "#rezhymy",
    },
    {
      id: "t5-23",
      topic: "Quicklook",
      question: "Який трафік підтримує Quicklook 2?",
      correct: "Тільки голос",
      wrong: ["Тільки файли", "Голос і дані одночасно", "Лише GPS-звіти", "Голос або пакетні дані"],
      explanation: "У таблиці режимів QL2 вказаний як голосовий.",
      reference: "#rezhymy",
    },
    {
      id: "t5-24",
      topic: "Quicklook 3",
      question: "Які швидкості ППРЧ має Quicklook 3?",
      correct: "Понад 100, 300 або 1000 разів/с",
      wrong: [
        "Тільки 10 разів/с",
        "Тільки 100 разів/с",
        "10000 разів/с без інших режимів",
        "Понад 50, 200 або 600 разів/с",
      ],
      explanation: "QL3 має повільний, середній і швидкий режими.",
      reference: "#rezhymy",
    },
    {
      id: "t5-25",
      topic: "Quicklook 3",
      question: "Що означає FCS?",
      correct: "Пошук вільного каналу",
      wrong: [
        "Фіксоване шифрування",
        "Форматування файлової системи",
        "Керування живленням",
        "Фіксоване сканування частоти",
      ],
      explanation: "Free Channel Search автоматично уникає поганих каналів.",
      reference: "#rezhymy",
    },
    {
      id: "t5-26",
      topic: "Quicklook 3",
      question: "Яка точність ручної синхронізації TOD потрібна QL3?",
      correct: "У межах +/- 1 хв",
      wrong: [
        "У межах +/- 10 хв",
        "У межах +/- 1 с",
        "Синхронізація не потрібна",
        "У межах +/- 5 хв",
      ],
      explanation: "QL3 синхронізують вручну в межах хвилини або через GPS.",
      reference: "#rezhymy",
    },
    {
      id: "t5-27",
      topic: "Quicklook Wide",
      question: "Який доступ до каналу обов'язковий для QLW?",
      correct: "MACA2",
      wrong: ["Legacy MACA лише", "Без доступу до каналу", "Тільки CSMA Wi-Fi", "TDMA без MACA2"],
      explanation: "Quicklook Wide потребує MACA2.",
      reference: "#rezhymy",
    },
    {
      id: "t5-28",
      topic: "Quicklook Wide",
      question: "Яка ширина каналу QLW?",
      correct: "75 кГц",
      wrong: ["5 кГц", "25 кГц", "1,2 МГц", "50 кГц"],
      explanation: "QLW є широким варіантом Quicklook зі смугою 75 кГц.",
      reference: "#rezhymy",
    },
    {
      id: "t5-29",
      topic: "Quicklook Wide",
      question: "Яка швидкість даних QLW при понад 100 перескоках/с?",
      correct: "64 кбіт/с",
      wrong: ["16 кбіт/с", "192 кбіт/с", "1372 кбіт/с", "128 кбіт/с"],
      explanation: "У режимі понад 100 hops/s наводиться 64 кбіт/с.",
      reference: "#rezhymy",
    },
    {
      id: "t5-30",
      topic: "TNW",
      question: "На чому базується розподіл доступу в TNW?",
      correct: "На TDMA і часових слотах",
      wrong: [
        "На одній безперервній передачі",
        "Лише на AM",
        "На механічному перемиканні",
        "На CSMA і випадкових затримках",
      ],
      explanation: "TNW є вузькосмуговою ППРЧ мережею з TDMA.",
      reference: "#rezhymy",
    },
    {
      id: "t5-31",
      topic: "TNW",
      question: "Яка точність ручної TOD-синхронізації TNW?",
      correct: "У межах +/- 1,5 хв",
      wrong: ["У межах +/- 1 с", "У межах +/- 10 хв", "Не потребує часу", "У межах +/- 30 с"],
      explanation: "TNW допускає ручну синхронізацію в межах півтори хвилини або GPS.",
      reference: "#rezhymy",
    },
    {
      id: "t5-32",
      topic: "CWR",
      question: "На чому побудована CWR?",
      correct: "На Fixed Frequency і MACA2",
      wrong: [
        "На Quicklook 2 без MACA",
        "На AM-мовленні",
        "На супутниковому STC лише",
        "На TNW і TDMA",
      ],
      explanation: "Country Wide Repeater використовує FF-мережу з MACA2 та IP-магістраль.",
      reference: "#rezhymy",
    },
    {
      id: "t5-33",
      topic: "CWR",
      question:
        "Що відбувається з абонентською радіостанцією CWR під час переходу в зону покриття іншого ретрансляторного вузла?",
      correct: "Вона автоматично реєструється на доступному новому вузлі",
      wrong: [
        "Оператор вручну реєструє станцію на новому вузлі",
        "Зв'язок припиняється до повернення в зону попереднього вузла",
        "Станція продовжує працювати тільки через попередній вузол",
        "Вона очікує ручного підтвердження переходу оператором",
        "Вона реєструється на новому вузлі лише після ручного перезапуску",
        "Вона залишається прив'язаною до попереднього вузла до втрати живлення",
      ],
      explanation:
        "У CWR термін stage означає ретрансляторний вузол або точку доступу до IP-магістралі. Автоматична реєстрація дає абонентській радіостанції змогу продовжити роботу в зоні іншого вузла.",
      reference: "#rezhymy",
    },
    {
      id: "t5-34",
      topic: "ANW2C",
      question: "Який тип мережі ANW2C?",
      correct: "Адаптивна широкосмугова MANET",
      wrong: [
        "Лише аналогова телефонна",
        "Одноканальна AM",
        "Тільки супутникова",
        "Централізована вузькосмугова TDMA-мережа",
      ],
      explanation: "ANW2C поєднує FF/LOS і TDMA в мобільній ad hoc мережі.",
      reference: "#rezhymy",
    },
    {
      id: "t5-35",
      topic: "ANW2C",
      question: "Скільки радіостанцій підтримує локальна мережа ANW2C?",
      correct: "До 30",
      wrong: ["До 13", "До 100", "До 1022", "До 50"],
      explanation: "У конспекті наведено до 30 радіо в локальній мережі.",
      reference: "#rezhymy",
    },
    {
      id: "t5-36",
      topic: "ANW2C",
      question: "Яка ширина каналу ANW2C?",
      correct: "1,2 МГц",
      wrong: ["25 кГц", "75 кГц", "5 МГц", "2,4 МГц"],
      explanation: "ANW2C використовує широкосмуговий канал 1,2 МГц.",
      reference: "#rezhymy",
    },
    {
      id: "t5-37",
      topic: "ANW2C",
      question: "Яка максимальна швидкість ANW2C наведена в конспекті?",
      correct: "1372 кбіт/с",
      wrong: ["64 кбіт/с", "192 кбіт/с", "2400 біт/с", "768 кбіт/с"],
      explanation: "Для ANW2C вказано до 1372 кбіт/с.",
      reference: "#rezhymy",
    },
    {
      id: "t5-38",
      topic: "STC",
      question: "Що означає STC?",
      correct: "Satellite TDMA Capability",
      wrong: [
        "Secure Tactical Channel",
        "Simple Transmit Control",
        "Stored Time Configuration",
        "Satellite Tactical Channel",
      ],
      explanation: "STC забезпечує TDMA роботу через супутниковий ретранслятор.",
      reference: "#rezhymy",
    },
    {
      id: "t5-39",
      topic: "STC",
      question: "Які смуги супутникових каналів STC?",
      correct: "25 кГц або 5 кГц",
      wrong: ["75 кГц або 1,2 МГц", "200 кГц лише", "2,4 МГц або 5 МГц", "25 кГц або 75 кГц"],
      explanation: "STC підтримує 25-кГц та вузькі 5-кГц канали.",
      reference: "#rezhymy",
    },
    {
      id: "t5-40",
      topic: "Потужність",
      question: "Яка потужність MEDIUM?",
      correct: "2 Вт",
      wrong: ["0,25 Вт", "5 Вт", "10 Вт", "1 Вт"],
      explanation: "Середній рівень передавача становить 2 Вт.",
      reference: "#potuzhnist",
    },
    {
      id: "t5-41",
      topic: "Потужність",
      question: "Яка потужність HIGH?",
      correct: "5 Вт",
      wrong: ["1 Вт", "2 Вт", "10 Вт", "7 Вт"],
      explanation: "HIGH відповідає 5 Вт.",
      reference: "#potuzhnist",
    },
    {
      id: "t5-42",
      topic: "Потужність",
      question: "Яка потужність HIGH+?",
      correct: "10 Вт короткочасно",
      wrong: ["2 Вт постійно", "5 Вт лише з GPS", "25 Вт без обмежень", "15 Вт короткочасно"],
      explanation: "HIGH+ дає до 10 Вт і призначений для короткочасної роботи.",
      reference: "#potuzhnist",
    },
    {
      id: "t5-43",
      topic: "Потужність",
      question: "Який LOW у мережі без MACA2?",
      correct: "0,25 Вт",
      wrong: ["1 Вт", "2 Вт", "5 Вт", "0,5 Вт"],
      explanation: "Без MACA2 низький рівень є нелінійним 0,25 Вт.",
      reference: "#potuzhnist",
    },
    {
      id: "t5-44",
      topic: "Потужність",
      question: "Який LOW у мережі з MACA2?",
      correct: "1 Вт",
      wrong: ["0,25 Вт", "5 Вт", "10 Вт", "2 Вт"],
      explanation: "Для лінійної роботи MACA2 LOW відповідає 1 Вт.",
      reference: "#potuzhnist",
    },
    {
      id: "t5-45",
      topic: "Живлення",
      question: "Яка номінальна напруга Li-ion АКБ?",
      correct: "10,8 В",
      wrong: ["7,2 В", "12 В", "24 В", "14,4 В"],
      explanation: "У конспекті наведено батарею 10,8 В.",
      reference: "#chyslovi-kharakterystyky",
    },
    {
      id: "t5-46",
      topic: "Живлення",
      question: "Який середній заявлений час роботи АКБ?",
      correct: "Близько 18 год",
      wrong: ["Близько 2 год", "Близько 6 год", "Близько 48 год", "Близько 12 год"],
      explanation: "Орієнтир 18 год наведено для циклу 10/10/80 при +20 °C.",
      reference: "#chyslovi-kharakterystyky",
    },
    {
      id: "t5-47",
      topic: "Живлення",
      question: "Наскільки приблизно зменшується ресурс АКБ при -20 °C?",
      correct: "На 20-25%",
      wrong: ["На 1-2%", "На 50-60%", "Не змінюється", "На 30-35%"],
      explanation: "Низька температура помітно знижує доступну ємність.",
      reference: "#chyslovi-kharakterystyky",
    },
    {
      id: "t5-48",
      topic: "Захищеність",
      question: "На яку глибину допускається занурення?",
      correct: "До 5 м",
      wrong: ["До 0,5 м", "До 20 м", "Занурення не допускається", "До 3 м", "До 1 м", "До 2 м"],
      explanation: "Специфікація вказує занурення до 5 метрів.",
      reference: "#chyslovi-kharakterystyky",
    },
    {
      id: "t5-49",
      topic: "Антенний порт",
      question: "Який опір антенного порту?",
      correct: "50 Ом",
      wrong: ["4 Ом", "25 Ом", "75 Ом", "100 Ом", "10 Ом", "300 Ом"],
      explanation: "Основний TNC-порт має хвильовий опір 50 Ом.",
      reference: "#chyslovi-kharakterystyky",
    },
    {
      id: "t5-50",
      topic: "Безпека",
      question: "Чи можна торкатися антени під час передачі?",
      correct: "Ні",
      wrong: [
        "Так, на LOW",
        "Так, у рукавицях",
        "Так, якщо PTT не натиснуто",
        "Так, якщо передавач працює без голосової модуляції",
        "Так, якщо передаються лише дані",
        "Так, якщо встановлено мінімальну потужність",
      ],
      explanation: "Передача даних може увімкнути випромінювання навіть без PTT.",
      reference: "#bezpeka",
    },
    {
      id: "t5-51",
      topic: "Безпека",
      question: "До якої температури заборонено нагрівати Li-ion АКБ?",
      correct: "Понад 71 °C",
      wrong: ["Понад 21 °C", "Понад 40 °C", "Понад 100 °C", "Понад 60 °C"],
      explanation: "Посібник забороняє вплив температур понад 160 °F, тобто 71 °C.",
      reference: "#bezpeka",
    },
    {
      id: "t5-52",
      topic: "Підготовка",
      question: "Що перевіряють перед установленням антени?",
      correct: "Чистоту роз'ємів і відсутність пошкоджень",
      wrong: [
        "Опір антени мультиметром",
        "Напругу на антенному роз'ємі",
        "КСХ без підключеної антени",
        "Стан захисного ковпачка після встановлення антени",
        "Справність антенного узгоджувача",
        "Рівень прийнятого сигналу",
      ],
      explanation: "Металева стружка або сміття можуть пошкодити ВЧ роз'єм.",
      reference: "#pidhotovka",
    },
    {
      id: "t5-53",
      topic: "Керування",
      question: "Як розблокувати передню панель?",
      correct: "Швидко натиснути CLR п'ять разів",
      wrong: [
        "Натиснути PTT десять разів",
        "Повернути перемикач у Z",
        "Зняти батарею",
        "Одночасно натиснути CLR і ENT",
        "Утримувати ENT п'ять секунд",
        "Одночасно натиснути PTT і 1 SQL",
      ],
      explanation: "П'ять швидких натискань CLR знімають блокування.",
      reference: "#orhany-keruvannia",
    },
    {
      id: "t5-54",
      topic: "ZEROIZE",
      question: "Що робить положення перемикача Z?",
      correct: "Очищує всі змінні, ключі й дані користувача",
      wrong: [
        "Вмикає GPS",
        "Зменшує потужність",
        "Запускає сканування",
        "Очищує лише поточну мережу",
        "Відновлює заводські частоти",
        "Блокує передню панель",
      ],
      explanation: "Z виконує повне незворотне ZEROIZE.",
      reference: "#praktychni-funktsii",
    },
    {
      id: "t5-55",
      topic: "Сканування",
      question: "У яких мережах доступне сканування?",
      correct: "У Fixed Frequency",
      wrong: [
        "У всіх ППРЧ",
        "Тільки в TNW",
        "Тільки в STC",
        "У Fixed Frequency та Quicklook 1A",
        "Тільки в ANW2C",
        "Тільки в Quicklook 1A",
      ],
      explanation: "Сканування не працює в hopping-режимах і MACA-мережах.",
      reference: "#praktychni-funktsii",
    },
    {
      id: "t5-56",
      topic: "ППРЧ",
      question: "Що таке Hopset?",
      correct: "Набір частот для швидкого перестроювання",
      wrong: [
        "Список заборонених частот",
        "Ключ AES",
        "Рівень потужності",
        "Порядок переходу між каналами без переліку частот",
      ],
      explanation: "Hopset визначає частоти, між якими стрибає радіостанція.",
      reference: "#praktychni-funktsii",
    },
    {
      id: "t5-57",
      topic: "ППРЧ",
      question: "Що таке Lockset?",
      correct: "Частоти, заборонені для використання під час ППРЧ",
      wrong: [
        "Набір робочих частот",
        "Список контактів",
        "Ключі шифрування",
        "Частоти пріоритетного сканування",
      ],
      explanation: "Lockset виключає частоти через нормативні чи оперативні обмеження.",
      reference: "#praktychni-funktsii",
    },
    {
      id: "t5-58",
      topic: "Dual PTT",
      question: "Коли доступний Dual PTT?",
      correct: "У двох Fixed Frequency мережах без MACA",
      wrong: [
        "Лише в Quicklook 2",
        "Тільки в STC",
        "У будь-якій MACA2 мережі",
        "У двох Fixed Frequency мережах із MACA2",
        "У двох MACA2-мережах",
        "У мережах ANW2C і TNW",
      ],
      explanation: "Верхня й нижня PTT працюють з первинною та вторинною FF-мережами.",
      reference: "#praktychni-funktsii",
    },
    {
      id: "t5-59",
      topic: "BIT",
      question: "Де запускають Built-In Test?",
      correct: "7 APPS > BUILT IN TEST",
      wrong: [
        "1 SQL > POWER",
        "Перемикачем Z",
        "Через PTT2",
        "9 PGM > APP > BUILT IN TEST",
        "7 APPS > RADIO INFO",
        "1 SQL > GPS > TEST",
      ],
      explanation: "BIT доступний у прикладному меню радіостанції через кнопку 7 APPS.",
      reference: "#dostup-ta-obsluhovuvannia",
    },
    {
      id: "t5-60",
      topic: "Обслуговування",
      question: "Що потрібно робити щодня під час експлуатації?",
      correct: "Виконувати Self Test",
      wrong: [
        "Повністю розбирати радіостанцію",
        "Форматувати файлову систему",
        "Замінювати всі ключі",
        "Перевіряти лише заряд батареї",
        "Щодня виконувати ZEROIZE",
        "Щодня змінювати антенний порт",
      ],
      explanation: "Щоденна профілактика починається із самотестування.",
      reference: "#dostup-ta-obsluhovuvannia",
    },
    {
      id: "t5-61",
      topic: "Quicklook 1A",
      question: "Яка швидкість даних у режимі QL1A?",
      correct: "16 кбіт/с",
      wrong: ["2,4 кбіт/с", "64 кбіт/с", "192 кбіт/с", "32 кбіт/с", "9,6 кбіт/с", "120 кбіт/с"],
      explanation: "Quicklook 1A використовує канал 25 кГц і забезпечує швидкість даних 16 кбіт/с.",
      reference: "#rezhymy",
    },
    {
      id: "t5-64",
      topic: "Fixed Frequency",
      question: "Який крок сітки FIX доступний через CPA?",
      correct: "1 Гц",
      wrong: ["5 кГц", "10 кГц", "25 кГц", "5 Гц"],
      explanation:
        "Через CPA частоту FIX можна задавати з кроком 1 Гц; вручну з передньої панелі - 10 Гц.",
      reference: "#rezhymy",
    },
    {
      id: "t5-65",
      topic: "ППРЧ",
      question: "Який крок сітки мають Quicklook і TNW?",
      correct: "25 кГц",
      wrong: ["1 Гц", "5 кГц", "75 кГц", "10 кГц"],
      explanation: "У режимах Quicklook і TNW частотна сітка має крок 25 кГц.",
      reference: "#rezhymy",
    },
    {
      id: "t5-66",
      topic: "ANW2C",
      question: "Який крок частотної сітки ANW2C?",
      correct: "5 кГц",
      wrong: ["1 Гц", "25 кГц", "1,2 МГц", "10 кГц"],
      explanation: "Для ANW2C у таблиці мереж наведено крок сітки 5 кГц.",
      reference: "#rezhymy",
    },
    {
      id: "t5-67",
      topic: "TNW",
      question: "Яка швидкість GPS-даних у TNW?",
      correct: "2,4 кбіт/с",
      wrong: ["14 кбіт/с", "64 кбіт/с", "192 кбіт/с", "4,8 кбіт/с"],
      explanation: "TNW забезпечує 2,4 кбіт/с для GPS-даних.",
      reference: "#rezhymy",
    },
    {
      id: "t5-68",
      topic: "TNW",
      question: "Яка швидкість IP-даних у TNW?",
      correct: "14 кбіт/с",
      wrong: ["2,4 кбіт/с", "16 кбіт/с", "1372 кбіт/с", "28 кбіт/с"],
      explanation: "Для IP-даних у TNW наведено швидкість 14 кбіт/с.",
      reference: "#rezhymy",
    },
    {
      id: "t5-69",
      topic: "TNW",
      question: "Як у TNW визначається Time Master?",
      correct: "Автоматично",
      wrong: [
        "Лише вручну оператором",
        "За найвищою потужністю передавача",
        "Фіксовано для станції з номером 1",
        "За найменшим номером станції",
      ],
      explanation: "TNW автоматично обирає Time Master для часової синхронізації мережі.",
      reference: "#rezhymy",
    },
    {
      id: "t5-70",
      topic: "STC",
      question: "Який діапазон приймання STC?",
      correct: "243-270 МГц",
      wrong: ["30-108 МГц", "225,6-512 МГц", "291-318,3 МГц", "225,6-243 МГц"],
      explanation: "У STC приймання ведеться в діапазоні 243-270 МГц.",
      reference: "#rezhymy",
    },
    {
      id: "t5-71",
      topic: "STC",
      question: "Який діапазон передавання STC?",
      correct: "291-318,3 МГц",
      wrong: ["243-270 МГц", "30-107,075 МГц", "108,025-512 МГц", "270-291 МГц"],
      explanation: "У STC передавання ведеться в діапазоні 291-318,3 МГц.",
      reference: "#rezhymy",
    },
    {
      id: "t5-72",
      topic: "MACA2",
      question: "Для чого призначений MACA2?",
      correct: "Для запобігання колізіям під час багатостанційного обміну",
      wrong: [
        "Для збільшення потужності передавача",
        "Для супутникової синхронізації GPS",
        "Для очищення ключів шифрування",
        "Для розподілу часових слотів TNW",
      ],
      explanation:
        "MACA2 узгоджує доступ до каналу перед передаванням пакета, щоб станції не заважали одна одній.",
      reference: "#pryznachennia",
    },
    {
      id: "t5-73",
      topic: "MACA2",
      question:
        "Що може статися через надто довге утримання PTT у каналі зі спільним голосом і даними?",
      correct: "Можлива втрата даних",
      wrong: [
        "Автоматично виконується ZEROIZE",
        "Зростає швидкість даних",
        "Вмикається режим STC",
        "Голосовий трафік автоматично переходить у режим AM",
      ],
      explanation:
        "Тривала голосова передача займає спільний канал і може спричинити втрату пакетів даних.",
      reference: "#pryznachennia",
    },
    {
      id: "t5-76",
      topic: "Антени",
      question: "Яку довжину мають коротка й довга стрічкові антени?",
      correct: "30 см і 120 см",
      wrong: [
        "10 см і 30 см",
        "50 см і 100 см",
        "120 см і 240 см",
        "45 см і 150 см",
        "25 см і 100 см",
        "30 см і 90 см",
      ],
      explanation: "У комплекті можуть бути коротка стрічкова антена 30 см і довга 120 см.",
      reference: "#pidhotovka",
    },
    {
      id: "t5-77",
      topic: "Заряджання",
      question: "Що означає оранжевий індикатор зарядного пристрою?",
      correct: "Батарея заряджається",
      wrong: [
        "Батарея повністю заряджена",
        "Виявлено проблему з АКБ",
        "Зарядний пристрій вимкнений",
        "Батарея проходить перевірку стану",
      ],
      explanation: "Оранжевий індикатор показує поточне заряджання батареї.",
      reference: "#pidhotovka",
    },
    {
      id: "t5-78",
      topic: "Заряджання",
      question: "Які стани позначають зелений і червоний індикатори зарядного пристрою?",
      correct: "Зелений - заряджено; червоний - проблема з АКБ",
      wrong: [
        "Зелений - проблема; червоний - заряджено",
        "Обидва означають заряджання",
        "Зелений - перегрів; червоний - повний заряд",
        "Зелений - очікування; червоний - заряджання",
      ],
      explanation:
        "Зелений індикатор означає завершення заряджання, а червоний сигналізує про проблему з батареєю.",
      reference: "#pidhotovka",
    },
    {
      id: "t5-79",
      topic: "Доступ",
      question: "Які облікові дані використовуються для входу користувача Level 3?",
      correct: "level3 / hh03",
      wrong: ["level2 / hh02", "admin / admin", "operator / 0000", "level3 / hh04"],
      explanation:
        "Для Communications Officer (Level 3) використовуються ім'я level3 і пароль hh03.",
      reference: "#dostup-ta-obsluhovuvannia",
    },
    {
      id: "t5-80",
      topic: "Доступ",
      question: "Який мінімальний рівень потрібен для параметра KEEP LOGIN?",
      correct: "Level 2",
      wrong: ["Level 1", "Level 3", "Level 4", "Level 2 або Level 3 залежно від мережі"],
      explanation: "KEEP LOGIN зберігає вхід після циклу живлення і доступний починаючи з Level 2.",
      reference: "#dostup-ta-obsluhovuvannia",
    },
    {
      id: "t5-81",
      topic: "Моделі",
      question: "Який робочий діапазон RF-7800V-HH?",
      correct: "30-108 МГц",
      wrong: ["30-512 МГц", "108,025-512 МГц", "225,6-512 МГц", "30-174 МГц"],
      explanation: "RF-7800V-HH має вужчий діапазон, ніж RF-7850M-HH.",
      reference: "#modeli",
    },
    {
      id: "t5-82",
      topic: "Моделі",
      question:
        "Які режими з порівняльної таблиці доступні RF-7850M-HH, але недоступні RF-7800V-HH?",
      correct: "ANW2C та STC",
      wrong: ["FIX та QL1A", "QL2 та QL3", "QLW та TNW", "QL3 та ANW2C"],
      explanation: "Частоти ANW2C і STC лежать вище верхньої межі 108 МГц моделі RF-7800V-HH.",
      reference: "#modeli",
    },
    {
      id: "t5-83",
      topic: "Моделі",
      question: "Яка головна відмінність RF-7850M-HH від RF-7800V-HH?",
      correct: "Ширший діапазон до 512 МГц і підтримка режимів вище 108 МГц",
      wrong: [
        "Відсутність GPS",
        "Неможливість передавати голос",
        "Підтримка лише однієї мережі",
        "Вища потужність передавача за однакового діапазону",
      ],
      explanation: "RF-7850M-HH охоплює 30-512 МГц, тоді як RF-7800V-HH працює в межах 30-108 МГц.",
      reference: "#modeli",
    },
    {
      id: "t5-86",
      topic: "Моделі",
      question: "Які види сигналів недоступні RF-7800V-HH через верхню межу 108 МГц?",
      correct: "AM та ASK",
      wrong: ["FM та FSK", "MELP та CVSD", "FIX та QL1A", "AM та FM"],
      explanation:
        "AM і ASK для RF-7850M-HH використовуються вище 108 МГц, тому RF-7800V-HH їх не підтримує.",
      reference: "#modeli",
    },
    {
      id: "t5-87",
      topic: "Моделі",
      question: "Які вокодери є спільними для RF-7850M-HH і RF-7800V-HH?",
      correct: "MELP та CVSD",
      wrong: ["ME12 та ME6", "WBHF та XDL", "AM та ASK", "MELP та ME24"],
      explanation: "Обидві портативні моделі підтримують MELP 2400 біт/с і CVSD 16000 біт/с.",
      reference: "#modeli",
    },
    {
      id: "t5-88",
      topic: "Режими",
      question: "Який перелік режимів RF-7850M-HH відповідає узагальненій таблиці презентації?",
      correct: "FIX, QL1A, QL2, QL3, QLW, TNW, ANW2C, STC",
      wrong: [
        "FIX, ALE, HOP, 3G",
        "FIX, QL1A, QL2, 3G, QLW, TNW, ANW2C, STC",
        "Лише QL2 і QL3",
        "FIX, ALE, TNW, 3G+",
        "QL1A, HOP, QLW, STC",
        "FIX, QL1A, WBHF, XDL",
      ],
      explanation:
        "Узагальнена таблиця презентації наводить FIX, п'ять мереж Quicklook/TNW та високочастотні ANW2C і STC. CWR розглядається окремо.",
      reference: "#rezhymy",
    },
    {
      id: "t5-89",
      topic: "MACA",
      question: "Що робить MACA?",
      correct: "Керує множинним доступом і запобігає колізіям під час передавання голосу та даних",
      wrong: [
        "Визначає координати за GPS",
        "Змінює вихідну потужність",
        "Працює лише як голосовий вокодер",
        "Стирає ключі шифрування",
        "Завантажує конфігурацію з флеш-накопичувача",
        "Вмикає супутниковий ретранслятор",
      ],
      explanation:
        "MACA розділяє передавання даних на сегменти та дає змогу передавати голос і дані одним каналом без взаємних колізій.",
      reference: "#pryznachennia",
    },
    {
      id: "t5-90",
      topic: "TNW",
      question: "Які режими ретранслятора підтримує TNW?",
      correct: "Black і Red",
      wrong: [
        "Red і Green",
        "Blue і Black",
        "Red і Blue",
        "Black і Green",
        "Green і Blue",
        "Лише White",
      ],
      explanation: "У TNW голосовий ретранслятор може працювати в режимі Black або Red.",
      reference: "#rezhymy",
    },
    {
      id: "t5-91",
      topic: "Практика",
      question: "Який шлях відкриває RADIO NAME на RF-7850M-HH?",
      correct: "9 PGM → APP → MISC → RADIO NAME",
      wrong: [
        "7 APPS → MISC → RADIO NAME",
        "9 PGM → APP → CONFIG → MISC → RADIO NAME",
        "7 APPS → FILL RADIO → RADIO NAME",
        "9 PGM → IP CONFIG → RADIO NAME",
        "CALL MENU → NAVIGATION → RADIO NAME",
        "9 PGM → RT → NET MANAGER → RADIO NAME",
      ],
      explanation:
        "На RF-7850M-HH ім'я станції переглядають через 9 PGM → APP → MISC, після чого переходять до поля RADIO NAME.",
      reference: "#radio-info",
    },
    {
      id: "t5-92",
      topic: "Практика",
      question: "Як завантажити файл конфігурації з флеш-накопичувача?",
      correct: "7 APPS → FILL RADIO → FILL FROM FILE → EXTUSBDRIVE* → файл конфігурації",
      wrong: [
        "9 PGM → APP → IP CONFIG → FILL FROM FILE",
        "7 APPS → FILE BROWSER → INBOX → EXTUSBDRIVE*",
        "9 PGM → FILL RADIO → FILL FROM FILE → EXTUSBDRIVE*",
        "7 APPS → BUILT IN TEST → EXTUSBDRIVE*",
        "CALL MENU → NAVIGATION → FILL RADIO",
        "9 PGM → MISC → FILL FROM FILE",
      ],
      explanation:
        "Презентація показує шлях через 7 APPS, FILL RADIO та FILL FROM FILE до каталогу EXTUSBDRIVE*.",
      reference: "#flash-config",
    },
    {
      id: "t5-93",
      topic: "Практика",
      question: "Який шлях веде до статичної IP-адреси RF-7850M-HH?",
      correct: "9 PGM → APP → IP CONFIG → NETWORK ADAPTER → ETHERNET → STATIC ADDRESS",
      wrong: [
        "7 APPS → ETHERNET → NETWORK ADAPTER → STATIC IP",
        "8 APP → IP CONFIG → NET → STATIC IP",
        "9 PGM → MISC → ETHERNET → STATIC ADDRESS",
        "7 APPS → FILL RADIO → IP CONFIG",
        "CALL MENU → NAVIGATION → STATIC ADDRESS",
        "9 PGM → RT → GPS → IP ADDRESS",
      ],
      explanation:
        "Статичну адресу RF-7850M-HH переглядають через APP, IP CONFIG, NETWORK ADAPTER, ETHERNET і STATIC ADDRESS.",
      reference: "#static-ip",
    },
    {
      id: "t5-94",
      topic: "Voice Mail",
      question: "У яких режимах передають записане голосове повідомлення Voice Mail?",
      correct: "У режимах пакетної роботи з MACA, TDMA або ANW2",
      wrong: [
        "Лише в QL2 і QL3",
        "У режимах без підтримки даних",
        "Тільки в аналоговому FM",
        "Лише через STC",
        "Тільки у FIX без MACA",
        "Лише під час Built-In Test",
      ],
      explanation:
        "Voice Mail передається як дані, тому в тесті його пов'язують із мережами пакетної роботи MACA, TDMA та ANW2. Максимальна тривалість запису - 60 секунд.",
      reference: "#tac-chat",
    },
    {
      id: "t5-95",
      topic: "Час і дата",
      question: "Який шлях відкриває налаштування часу й дати?",
      correct: "7 APPS → TIME AND DATE",
      wrong: [
        "9 PGM → APP → TIME AND DATE",
        "7 APPS → GPS → TIME",
        "9 PGM → MISC → DATE",
        "CALL MENU → TIME AND DATE",
        "7 APPS → IP CONFIG → TIME",
        "9 PGM → NETWORK ADAPTER → UTC",
      ],
      explanation: "Дату й час радіостанції встановлюють у меню 7 APPS → TIME AND DATE.",
      reference: "#time-date",
    },
    {
      id: "t5-96",
      topic: "Час і дата",
      question: "Для чого призначена екранна клавіша UTC у меню TIME AND DATE?",
      correct: "Для зміни формату дати та внесення поправки часового поясу",
      wrong: [
        "Для синхронізації тільки через GPS",
        "Для очищення встановленого часу",
        "Для вибору мережі TNW",
        "Для запуску самотестування",
        "Для зміни статичної IP-адреси",
        "Для встановлення потужності передавача",
      ],
      explanation: "Клавіша UTC змінює формат дати й дає внести поправку часового поясу.",
      reference: "#time-date",
    },
    {
      id: "t5-97",
      topic: "Керування",
      question: "Якою фізичною клавішею перемикають екрани до появи меню NAVIGATION?",
      correct: "0 ↻",
      wrong: ["CALL MENU (трубка)", "7 APPS", "9 PGM", "1 SQL", "3 LT", "CLR"],
      explanation:
        "Клавіша 0 ↻ послідовно перемикає повний статус, головний екран TAC CHAT і короткий статус. CALL MENU є окремою екранною клавішею.",
      reference: "#tac-chat",
    },
    {
      id: "t5-98",
      topic: "Виклик",
      question: "Яка послідовність веде до індивідуального виклику?",
      correct: "0 ↻ → NAVIGATION → CALL MENU (трубка) → RADIO CONTACT → контакт",
      wrong: [
        "CALL MENU → NAVIGATION → RADIO CONTACT → контакт",
        "0 ↻ → NAVIGATION → >>> → MESSAGES → контакт",
        "7 APPS → CALL MENU → RADIO CONTACT → контакт",
        "9 PGM → APP → RADIO CONTACT → контакт",
        "0 ↻ → NAVIGATION → VOICE MAIL → контакт",
        "1 SQL → NAVIGATION → RADIO CONTACT → контакт",
      ],
      explanation:
        "Спочатку клавішею 0 ↻ відкривають NAVIGATION, потім обирають екранну клавішу CALL MENU з трубкою, RADIO CONTACT і потрібний контакт.",
      reference: "#tac-chat",
    },
    {
      id: "t5-exam-01",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Режим ретранслятора Black в режимі TNW дозволяє:",
      correct: "розташовувати радіостанцію в неконтрольованій зоні",
      wrong: [
        "розташовувати радіостанцію в контрольованій зоні",
        "працювати в аналоговому режимі",
        "ретранслювати трафік лише за наявності оператора біля станції",
        "використовувати станцію лише як абонентський термінал без ретрансляції",
        "ретранслювати лише аналоговий голос без цифрового трафіку",
        "працювати ретранслятором лише у FIX замість TNW",
      ],
      explanation:
        "У примітці до таблиці режимів прямо зазначено: Black допускає неконтрольоване розміщення з видаленими ключовими даними.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-02",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Який діапазон частот в режимі ANW2C при використанні радіостанцій RF-7850M-HH?",
      correct: "225,6-512 МГц",
      wrong: [
        "1,5-59,9999 МГц",
        "30-511,975 МГц",
        "30-108 МГц",
        "1,6-29,9999 МГц",
        "30-107,075 МГц",
        "136-174 МГц",
      ],
      explanation: "Рядок ANW2C: 225,6–512 МГц.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-03",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Яке відхилення по часу допускається на радіостанціях RF-7850M-HH при роботі в режимі Quicklook Wide?",
      correct: "до 1 хв",
      wrong: [
        "синхронізація по часу не вимагається",
        "до 7 хв",
        "до 1,5 хв",
        "до 9 хв",
        "до 2 хв",
        "до 3 хв",
      ],
      explanation: "Для QLW зазначено TOD ±1 хв або GPS.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-04",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Яка швидкість передачі даних при використанні радіостанцій RF-7850M-HH (RF-7800V-HH) в режимі Quicklook1A?",
      correct: "16 кбіт/сек",
      wrong: [
        "120 кбіт/сек",
        "64 кбіт/сек",
        "192 кбіт/сек",
        "1 Мбіт/сек",
        "1372 кбіт/сек",
        "32 кбіт/сек",
      ],
      explanation: "Рядок QL1A: 16 кбіт/с.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-05",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Який порядок визначення імені радіостанції HARRIS RF-7800V-HH/RF-7850M-HH?",
      correct: "9 PGM → APP → MISC → ↓ → RADIO NAME",
      wrong: [
        "9 PGM → APP → CONFIG → MISC → RADIO NAME",
        "7 APPS → MISC → RADIO NAME",
        "9 PGM → APP → RADIO NAME → MISC",
        "7 APPS → RADIO INFO → RADIO NAME",
        "9 PGM → RT → MISC → RADIO NAME",
        "9 PGM → APP → IP CONFIG → RADIO NAME",
      ],
      explanation:
        "Для RF-7850M-HH: 9 PGM → APP → MISC → CID → RADIO NAME. Стрілка ↓ у варіанті відповіді позначає перехід до поля імені. Для RF-7800V-HH шлях починається 9 PGM → MISC, без APP; оригінальний тест неточно об’єднує моделі.",
      reference: "#radio-info",
    },
    {
      id: "t5-exam-06",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Для рівня користувача LEVEL3 застосовується пароль:",
      correct: "hh03",
      wrong: ["03HH", "HH03", "hh02", "hh04", "03hh", "HH04"],
      explanation:
        "У таблиці рівнів користувача наведено вхід level3 / hh03. Регістр має значення.",
      reference: "#dostup-ta-obsluhovuvannia",
    },
    {
      id: "t5-exam-08",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Яке відхилення по часу допускається на радіостанціях RF-7850M-HH при роботі в режимі TNW?",
      correct: "до 1,5 хв",
      wrong: [
        "до 1 хв",
        "до 7 хв",
        "синхронізація по часу не вимагається",
        "до 9 хв",
        "до 2 хв",
        "до 3 хв",
      ],
      explanation: "Для TNW зазначено TOD ±1,5 хв або GPS.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-09",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Які типи модуляції використовуються на радіостанціях RF-7850M-HH?",
      correct: "AM, FM, FSK, ASK",
      wrong: [
        "AM, FM, FSK, CW",
        "AM, FM, ASK, USB",
        "AM, FM, FSK, LSB",
        "AM, FM, AME, AVS",
        "FM, FSK, USB, LSB",
        "AM, ASK, CW, USB",
      ],
      explanation:
        "Таблиця модуляцій містить AM, FM, ASK і FSK. CVSD — вокодер. На скриншоті дозволено обрати кілька відповідей. У цьому питанні всі правильні варіанти об’єднано в одну відповідь.",
      reference: "#moduliatsii",
    },
    {
      id: "t5-exam-10",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Який порядок завантаження файлу конфігурації з розширенням __.cpafill., за допомогою флеш-накопичувача в радіостанцію HARRIS RF-7850M-HH?",
      correct:
        "7 APPS → FILL RADIO → FILL FROM FILE → EXTUSBDRIVE1 → вибрати файл з відповідним ID → ENT",
      wrong: [
        "7 APPS → FILL RADIO → FILL FROM FILE → вибрати файл з відповідним ID → ENT",
        "9 PGM → FILL RADIO → FILL FROM FILE → INBOX → вибрати файл з відповідним ID → ENT",
        "7 APPS → FILL RADIO → FILL FROM FILE → INTERNAL → вибрати файл з відповідним ID → ENT",
        "7 APPS → FILL RADIO → FILL TO FILE → EXTUSBDRIVE1 → вибрати файл → ENT",
        "9 PGM → APP → FILL RADIO → EXTUSBDRIVE1 → вибрати файл → ENT",
        "7 APPS → FILE BROWSER → EXTUSBDRIVE1 → вибрати файл → ENT",
      ],
      explanation:
        "Конспект наводить 7 APPS → FILL RADIO → FILL FROM FILE → EXTUSBDRIVE* → файл *.cpafill.",
      reference: "#flash-config",
    },
    {
      id: "t5-exam-11",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Яка швидкість передачі даних при використанні радіостанцій RF-7850M-HH (RF-7800V-HH) в режимі TNW-75 з шириною каналу 75 кГц?",
      correct: "14 кбіт/сек",
      wrong: [
        "1372 кбіт/сек",
        "16 кбіт/сек",
        "2,4 кбіт/сек",
        "120 кбіт/сек",
        "1 Мбіт/сек",
        "192 кбіт/сек",
      ],
      explanation:
        "Для TNW наведено 14 кбіт/с IP-даних і окремо 2,4 кбіт/с GPS. Обрано швидкість IP-даних.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-13",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Яка ширина смуги каналу в режимі Quicklook1A при використанні радіостанцій RF-7850M-HH?",
      correct: "25 кГц",
      wrong: ["24 кГц", "3 кГц", "1,2 МГц", "75 кГц", "12,5 кГц", "50 кГц"],
      explanation: "Для QL1A ширина каналу — 25 кГц.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-15",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Режим Dual PTT:",
      correct: "дозволяє працювати в двох радіомережах, основній та додатковій",
      wrong: [
        "дозволяє працювати на одній частоті в одній мережі",
        "дозволяє працювати на двох різних частотах в одній мережі",
        "дозволяє працювати на прийом",
        "дозволяє працювати одночасно у трьох радіомережах",
        "дозволяє автоматично ретранслювати між двома мережами без участі користувача",
        "дозволяє одночасно передавати двома тангентами в одній мережі",
      ],
      explanation:
        "Підрозділ Dual PTT: робота з двома мережами FIX через дві тангенти, якщо MACA вимкнена.",
      reference: "#praktychni-funktsii",
    },
    {
      id: "t5-exam-17",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Який порядок проведення вбудованого тестування радіостанції HARRIS RF-7850M-HH?",
      correct:
        "7 APPS → BUILT IN TEST → NON-INTERACTIVE → екранна клавіша ► → дочекатись TEST STATUS 100 → клавіша I",
      wrong: [
        "8 → TEST → NON-INTERACTIVE → екранна клавіша ► → дочекатись TEST STATUS 100 → клавіша I",
        "9 PGM → BUILT IN TEST → NON-INTERACTIVE → екранна клавіша ► → дочекатись TEST STATUS 100 → клавіша I",
        "7 APPS → BUILT IN TEST → INTERACTIVE → екранна клавіша ► → TEST STATUS 100 → клавіша I",
        "7 APPS → RADIO INFO → NON-INTERACTIVE → TEST STATUS 100 → клавіша I",
        "9 PGM → APP → BUILT IN TEST → TEST STATUS 100 → клавіша I",
        "7 APPS → BUILT IN TEST → RESULTS → NON-INTERACTIVE → клавіша I",
      ],
      explanation:
        "Конспект підтверджує 7 APPS → BUILT IN TEST → NON-INTERACTIVE → TEST STATUS → RESULTS. Після завершення тесту відкривають результати. Позначення ► та I збережені з оригінальних варіантів екзаменаційного питання.",
      reference: "#dostup-ta-obsluhovuvannia",
    },
    {
      id: "t5-exam-18",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Режим TNW дозволяє використовувати такі режими ретрансляторів:",
      correct: "Black,Red",
      wrong: ["Red,Blue", "Blue,Black", "Black, Green", "Red,Green", "Black, White", "Red, White"],
      explanation: "Примітка «Ретранслятор TNW» прямо називає Black і Red.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-19",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Які застосовуються антени в радіостанціях RF-7850M-HH (RF-7800V-HH) для прийому/передачі?",
      correct: "стрічкова 30 см, стрічкова 120 см, виносна штирьова",
      wrong: [
        "стрічкова 30 см, стрічкова 120 см, виносна штирьова, gps",
        "дипольна, helical",
        "стрічкова 30 см, стрічкова 120 см",
        "стрічкова 30 см, стрічкова 90 см, виносна штирьова",
        "стрічкова 60 см, стрічкова 120 см, виносна штирьова",
        "тільки виносна штирьова та дипольна",
      ],
      explanation:
        "У комплекті є стрічкові антени 30/120 см та виносна штирьова. GPS-антена призначена для приймання навігаційного сигналу (у підготовці окремо вказано внутрішній GPS), а не для прийому/передачі радіозв’язку. Тому варіант a зайво включає GPS; правильний — d.",
      reference: "#pidhotovka",
    },
    {
      id: "t5-exam-20",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Яка швидкість передачі даних при використанні радіостанцій RF-7850M-HH (RF-7800V-HH) в режимі Quicklook Wide?",
      correct: "64 кбіт/сек",
      wrong: [
        "192 кбіт/сек",
        "16 кбіт/сек",
        "120 кбіт/сек",
        "1 Мбіт/сек",
        "32 кбіт/сек",
        "256 кбіт/сек",
      ],
      explanation: "Для QLW зазначено 64 кбіт/с.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-21",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Яка швидкість передачі даних при використанні радіостанцій RF-7850M-HH (RF-7800V-HH) в режимі FIX з шириною каналу 75 кГц?",
      correct: "192 кбіт/сек",
      wrong: [
        "16 кбіт/сек",
        "1372 кбіт/сек",
        "1 Мбіт/сек",
        "120 кбіт/сек",
        "64 кбіт/сек",
        "32 кбіт/сек",
      ],
      explanation:
        "У рядку FIX парі 25 / 75 кГц відповідає 64 / 192 кбіт/с. Для 75 кГц — 192 кбіт/с.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-22",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Режим ретранслятора Red в режимі TNW дозволяє:",
      correct: "розташовувати радіостанцію в контрольованій зоні",
      wrong: [
        "працювати в дуплексі",
        "працювати в режимі радіомовчання",
        "розташовувати радіостанцію в неконтрольованій зоні",
        "працювати на черговому прийомі",
        "працювати в аналоговому режимі",
        "працювати в режимі напівдуплексі",
      ],
      explanation: "У примітці до TNW: у Red станцію контролює користувач.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-23",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Яке відхилення по часу допускається на радіостанціях RF-7850M-HH при роботі в режимі Quicklook3?",
      correct: "до 1 хв",
      wrong: [
        "до 7 хв",
        "до 9 хв",
        "синхронізація по часу не вимагається",
        "до 1,5 хв",
        "до 2 хв",
        "до 3 хв",
      ],
      explanation: "QL3: TOD ±1 хв або GPS.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-24",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Який діапазон частот в режимі FF при використанні радіостанцій RF-7850M-HH?",
      correct: "30-512 МГц",
      wrong: [
        "30-108 МГц",
        "136-174 МГц",
        "1,5-59,9999 МГц",
        "1,5-29,9999 МГц",
        "30-511,975 МГц",
        "225,6-512 МГц",
      ],
      explanation: "Рядок FIX (фіксована частота, FF): RF-7850M — 30–512 МГц.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-25",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Які існують режими роботи радіостанції HARRIS RF-7850M-HH?",
      correct: "FF, QL1A, QL2, QL3, QLW, TNW, ANW2C, STC",
      wrong: [
        "FIX, ALE, HOP, 3G",
        "FIX, QL1A, QL2, 3G, QLW, TNW, ANW2C, STC",
        "FF, QL1A, QL2, QL3, QLW, TNW, ALE, STC",
        "FF, QL1A, QL2, QL3, QLW, HOP, ANW2C, STC",
        "FF, QL1A, QL2, QL3, QLW, TNW, ANW2C, 3G",
        "FF, QL1A, QL2, QL3, QLW, ALE, HOP, STC",
      ],
      explanation:
        "У конспекті є окремий «Перелік для тесту»: FIX, QL1A, QL2, QL3, QLW, TNW, ANW2C, STC. FF тут відповідає FIX.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-26",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Який діапазон частот в режимі TNW при використанні радіостанцій RF-7850M-HH?",
      correct: "30-511,975 МГц",
      wrong: [
        "30-108 МГц",
        "136-174 МГц",
        "1,6-29,9999 МГц",
        "30-107,075 МГц",
        "1,5-59,9999 МГц",
        "30-512 МГц",
      ],
      explanation: "TNW для RF-7850M: 30–511,975 МГц.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-27",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Який діапазон частот в режимі Quicklook Wide при використанні радіостанцій RF-7850M-HH?",
      correct: "30-511,975 МГц",
      wrong: [
        "136-174 МГц",
        "30-512 МГц",
        "30-107,075 МГц",
        "30-108 МГц",
        "1,5-59,9999 МГц",
        "1,6-29,9999 МГц",
      ],
      explanation:
        "QLW для RF-7850M: 30–511,975 МГц. 30–512 МГц — загальний діапазон і діапазон FIX; верхня межа QLW інша. Правильний варіант f.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-28",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Яка вихідна потужність радіостанції RF-7850M-HH?",
      correct: "1 / 2 / 5 / 10 Вт",
      wrong: ["0,1 / 1 / 4 Вт", "1 / 5 Вт", "20-54 Вт", "1 / 5 / 20 Вт", "1-55 Вт", "1-5 Вт"],
      explanation:
        "Наведено 1, 2, 5, 10 Вт. Уточнення конспекту: LOW без MACA2 може бути 0,25 Вт, а HIGH+ 10 Вт використовують короткочасно.",
      reference: "#potuzhnist",
    },
    {
      id: "t5-exam-29",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Яка ширина смуги каналу в режимі Quicklook Wide при використанні радіостанцій RF-7850M-HH?",
      correct: "75 кГц",
      wrong: ["1,2 МГц", "24 кГц", "25 кГц", "3 кГц", "12,5 кГц", "50 кГц"],
      explanation: "Для QLW вказано канал 75 кГц.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-30",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Які режими з MACA використовуються на радіостанціях HARRIS RF-7850M-HH (RF-7800V-HH)?",
      correct: "FF75, QLW, QL1A",
      wrong: [
        "FF75, QLW, ALE",
        "FF75, QLW, QL1A, QL2",
        "FF75, 3G, QL1A",
        "FF75, QLW, QL1A, QL3",
        "FF75, QL2, QL3",
        "QLW, QL2, QL3",
      ],
      explanation:
        "MACA вказана для FIX і QL1A, MACA2 — для QLW. QL2 та QL3 передають лише голос. Серед наведених переліків відповідає варіант 4.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-31",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Яка ширина смуги каналу в режимі STC при використанні радіостанцій RF-7850M-HH?",
      correct: "25 кГц",
      wrong: ["1,2 МГц", "24 кГц", "75 кГц", "3 кГц", "12,5 кГц", "50 кГц"],
      explanation:
        "Для STC конспект наводить 25 або 5 кГц. Серед запропонованих варіантів є лише 25 кГц; питання не охоплює обидві можливості.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-32",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Який порядок завантаження файлу конфігурації за допомогою флеш-накопичувача в радіостанцію RF-7850M-HH (RF-7800V-HH)?",
      correct:
        "7 APPS → FILL RADIO → FILL FROM FILE → EXTUSBDRIVE1 → вибрати відповідний файл конфігурації",
      wrong: [
        "8 PGM → APP → IP CONFIG → FILL FROM FILE → EXTUSBDRIVE1 → вибрати відповідний файл конфігурації",
        "9 PGM → FILL RADIO → FILL FROM FILE → EXTUSBDRIVE1 → вибрати відповідний файл конфігурації",
        "7 APPS → FILE BROWSER → INBOX → EXTUSBDRIVE1 → вибрати відповідний файл конфігурації",
        "7 APPS → FILL RADIO → FILL TO FILE → EXTUSBDRIVE1 → вибрати відповідний файл конфігурації",
        "7 APPS → FILL RADIO → FILL FROM FILE → INTERNAL → вибрати відповідний файл конфігурації",
        "9 PGM → APP → FILL RADIO → FILL FROM FILE → EXTUSBDRIVE1 → вибрати відповідний файл конфігурації",
      ],
      explanation: "Шлях повністю відповідає підрозділу про завантаження з флеш-накопичувача.",
      reference: "#flash-config",
    },
    {
      id: "t5-exam-34",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Який порядок визначення статичної IP адреси радіостанції HARRIS RF-7850M-HH (RF-7800V-HH)?",
      correct: "9 PGM → APP → IP CONFIG → NETWORK ADAPTERS → ETHERNET → STATIC ADDRESS",
      wrong: [
        "7 APPS → IP MENU → ETHERNET → NETWORK ADAPTERS → STATIC IP",
        "8 → APP → IP CONFIG → NET → STATIC IP",
        "9 PGM → APP → IP CONFIG → NETWORK ADAPTERS → USB → STATIC ADDRESS",
        "9 PGM → APP → MISC → ETHERNET → STATIC ADDRESS",
        "7 APPS → IP CONFIG → NETWORK ADAPTERS → ETHERNET → STATIC ADDRESS",
        "9 PGM → APP → IP CONFIG → STATIC ADDRESS → ETHERNET",
      ],
      explanation:
        "Для RF-7850M-HH конспект наводить 9 PGM → APP → IP CONFIG → NETWORK ADAPTER → ETHERNET → STATIC ADDRESS. Для RF-7800V-HH вхід до IP CONFIG без APP.",
      reference: "#static-ip",
    },
    {
      id: "t5-exam-35",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "В яких режимах можливо відправити голосове повідомлення на радіостанції HARRIS RF-7800V-HH/RF-7850M-HH?",
      correct: "В усіх режимах з MACA, TDMA та ANW2.",
      wrong: [
        "В режимах QL2 та QL3.",
        "В усіх режимах.",
        "Лише в режимі TNW.",
        "Лише в режимі ANW2C.",
        "Лише в режимах QL2, QL3 та STC.",
        "Лише в аналоговому FM без передавання даних.",
      ],
      explanation:
        "Voice Mail — записане голосове повідомлення, яке передається як дані. Конспект прямо пов’язує його з MACA, TDMA або ANW2.",
      reference: "#tac-chat",
    },
    {
      id: "t5-exam-36",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Яка загальна кількість мереж та кількість мереж яку можна обрати перемикачем на радіостанції HARRIS RF-7850M-HH?",
      correct: "25/13.",
      wrong: ["16/32.", "8/13.", "25/16.", "32/13.", "16/13.", "32/16."],
      explanation: "25 програмованих мереж; 13 доступні перемикачем.",
      reference: "#chyslovi-kharakterystyky",
    },
    {
      id: "t5-exam-37",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Що таке MACA на радіостанціях УКХ HARRIS?",
      correct:
        "Функція уникнення колізій під час одночасної передачі голосу та даних. Дозволяє здійснювати передачу даних.",
      wrong: [
        "Дозволяє визначати працездатність радіостанції.",
        "Дозволяє визначати якість радіоканалу.",
        "Функція автоматичної синхронізації часу без керування доступом до каналу.",
        "Функція вибору вихідної потужності передавача за рівнем сигналу.",
        "Функція зміни частоти за псевдовипадковим законом без керування доступом до каналу.",
        "Функція криптографічного захисту голосу та даних замість алгоритму шифрування.",
      ],
      explanation:
        "Конспект пояснює уникнення колізій MACA2 та використання одного каналу для голосу і даних. «Одночасно» тут не означає безперервне передавання двох сигналів: доступ до каналу узгоджується.",
      reference: "#pryznachennia",
    },
    {
      id: "t5-exam-38",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Яка швидкість передачі даних при використанні радіостанцій RF-7850M-HH (RF-7800V-HH) в режимі FIX з шириною каналу 25 кГц?",
      correct: "64 кбіт/сек",
      wrong: [
        "192 кбіт/сек",
        "1 Мбіт/сек",
        "120 кбіт/сек",
        "16 кбіт/сек",
        "1372 кбіт/сек",
        "32 кбіт/сек",
      ],
      explanation:
        "У рядку FIX парі 25 / 75 кГц відповідає 64 / 192 кбіт/с. Для 25 кГц — 64 кбіт/с.",
      reference: "#rezhymy",
    },
    {
      id: "t5-exam-40",
      topic: "Екзаменаційні питання · Harris УКХ",
      question: "Які типи вокодерів використовуються на радіостанціях RF-7850M-HH?",
      correct: "MELP, CVSD",
      wrong: ["MELP, DV24", "MELP, DV6", "CVSD, DV24", "CVSD, DV6", "DV24, DV6", "MELP, CLR"],
      explanation:
        "У конспекті наведено MELP 2400 біт/с та CVSD 16000 біт/с. На скриншоті дозволено обрати кілька відповідей. У цьому питанні всі правильні варіанти об’єднано в одну відповідь.",
      reference: "#vokodery",
    },
    {
      id: "t5-exam-12",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "Яка індикація зарядного пристрою до радіостанції RF-7850M-HH, якщо АКБ під’єднаний до неї, заряджається?",
      correct: "оранжевий постійний",
      wrong: [
        "зелений блимаючий",
        "червоний блимаючий",
        "оранжевий блимаючий",
        "зелений постійний",
        "червоний постійний",
        "індикатор не світиться",
      ],
      explanation:
        "Під час заряджання АКБ індикатор світиться постійно оранжевим. Постійний зелений означає завершення заряджання, постійний червоний — проблему з АКБ.",
      reference: "#pidhotovka",
    },
    {
      id: "t5-exam-14",
      topic: "Екзаменаційні питання · Harris УКХ",
      question:
        "В яких режимах потрібна обов’язкова синхронізація за часом при використанні радіостанцій RF-7850M-HH?",
      correct: "QL3, QLW, TNW, ANW2C",
      wrong: [
        "В усіх режимах",
        "QL1A, QL2, QL3, QLW, TNW, ANW2C",
        "синхронізація не потрібна взагалі",
        "QL2, QL3, QLW, TNW, ANW2C",
        "FF, QL1A, QL2, QL3, QLW, TNW, STC",
        "QL3, QLW, TNW — без ANW2C",
      ],
      explanation:
        "Правильний перелік — QL3, QLW, TNW, ANW2C. Для ANW2C також потрібен узгоджений час; самоорганізація мережі не означає відсутності часової синхронізації. Числовий допуск часу для RF-7850M-HH у конспекті не встановлено.",
      reference: "#rezhymy",
    },
  ],
};
